spring:
  application:
    name: inserter
  datasource:
    url: jdbc:mysql://localhost:3306/old_db?useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false